### ISSUE TITLE
iPhone 5c effects not appearing when selecting iPhone 5c as device in Screentaker

### ISSUE THREAD

**Issue by fabiankr** [ruddfawcett/Screentaker-Plugins#1]
The iPhone 5c effects should return YES for the FKScreenshotEffectDeviceiPhone5c constant and not FKScreenshotEffectDeviceiPhone5s. RF5CColorEffect.m line 35 needs to be changed: https://github.com/rexfinn/Screentaker-Plugins/blob/master/5c_colors/RF5CColorEffect.m#L35

Keep up the great work!

**Comment by ruddfawcett** [comment]
Ahh of course!  I knew I forgot something!  Thanks!

**Comment by ruddfawcett** [comment]
@fabiankr is this fixed via #2?  Didn't get much of a chance to look at it.

**Comment by fabiankr** [comment]
Yes, it is.

**Comment by ruddfawcett** [comment]
@fabiankr great, thanks!
